[package]
name = "sysctl-cpu"
version = "0.1.0"
edition = "2024"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "forbid"

[dependencies.rs-sysctl-typed-cpu]
path = "../../.."

[dependencies.serde_json]
version = "1"
features = [
	"std",
]

